[package]
name = "es-logger"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
serde = "~1"
serde_json = "~1"
elasticsearch = "8.4.0-alpha.1"
tokio = { version = "*", features = ["full"] }
