[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
config = "0.11"
tokio = { version = "1", features = [ "macros", "rt-multi-thread" ] }
serde = { version = "1", features = [ "derive" ] }